[phases.setup]
nixPkgs = ["nodejs", "python3", "python3Packages.pip", "ffmpeg"]

[phases.build]
cmds = [
    "npm install",
    "python3 -m pip install --no-cache-dir yt-dlp"
]

[start]
cmd = "node server.js"
